"""create auth sessions table

Revision ID: 2c5b31990a03
Revises: 30f8e0bdc666
Create Date: 2026-08-13 21:27:56.695189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c5b31990a03"
down_revision: str | Sequence[str] | None = "30f8e0bdc666"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=False),
        sa.Column("token_family_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=64), nullable=True),
        sa.Column("replaced_by_session_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "expires_at > created_at",
            name=op.f("ck_auth_sessions_expiration_after_creation"),
        ),
        sa.CheckConstraint(
            "replaced_by_session_id IS NULL OR replaced_by_session_id <> id",
            name=op.f("ck_auth_sessions_cannot_replace_itself"),
        ),
        sa.CheckConstraint(
            "replaced_by_session_id IS NULL OR rotated_at IS NOT NULL",
            name=op.f("ck_auth_sessions_replacement_requires_rotation"),
        ),
        sa.CheckConstraint(
            "revoke_reason IS NULL OR revoked_at IS NOT NULL",
            name=op.f("ck_auth_sessions_reason_requires_revocation"),
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= created_at",
            name=op.f("ck_auth_sessions_revocation_after_creation"),
        ),
        sa.CheckConstraint(
            "rotated_at IS NULL OR rotated_at >= created_at",
            name=op.f("ck_auth_sessions_rotation_after_creation"),
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_session_id"],
            ["app.auth_sessions.id"],
            name=op.f("fk_auth_sessions_replaced_by_session_id_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint(
            "refresh_token_hash", name=op.f("uq_auth_sessions_refresh_token_hash")
        ),
        schema="app",
    )
    op.create_index(
        "ix_auth_sessions_expires_at",
        "auth_sessions",
        ["expires_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_auth_sessions_token_family",
        "auth_sessions",
        ["token_family_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_auth_sessions_user_revoked",
        "auth_sessions",
        ["user_id", "revoked_at"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_auth_sessions_user_revoked", table_name="auth_sessions", schema="app"
    )
    op.drop_index(
        "ix_auth_sessions_token_family", table_name="auth_sessions", schema="app"
    )
    op.drop_index(
        "ix_auth_sessions_expires_at", table_name="auth_sessions", schema="app"
    )
    op.drop_table("auth_sessions", schema="app")
    # ### end Alembic commands ###
