"""create assistant runs table

Revision ID: 4f7571eb0cd0
Revises: 8232604507a7
Create Date: 2026-08-17 18:13:46.686813

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f7571eb0cd0"
down_revision: str | Sequence[str] | None = "8232604507a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_message_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'processing'"),
            nullable=False,
        ),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'processing' AND claim_token IS NOT NULL AND lease_expires_at IS NOT NULL AND assistant_message_id IS NULL AND last_error_code IS NULL) OR (status = 'completed' AND claim_token IS NULL AND lease_expires_at IS NULL AND assistant_message_id IS NOT NULL AND last_error_code IS NULL) OR (status = 'failed' AND claim_token IS NULL AND lease_expires_at IS NULL AND assistant_message_id IS NULL AND last_error_code IS NOT NULL)",
            name=op.f("ck_assistant_runs_state_shape"),
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed')",
            name=op.f("ck_assistant_runs_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 1", name=op.f("ck_assistant_runs_attempt_count_positive")
        ),
        sa.CheckConstraint(
            "last_error_code IS NULL OR char_length(btrim(last_error_code)) BETWEEN 1 AND 64",
            name=op.f("ck_assistant_runs_error_code_length"),
        ),
        sa.CheckConstraint(
            "lease_expires_at IS NULL OR lease_expires_at > created_at",
            name=op.f("ck_assistant_runs_lease_after_creation"),
        ),
        sa.ForeignKeyConstraint(
            ["assistant_message_id"],
            ["app.messages.id"],
            name=op.f("fk_assistant_runs_assistant_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id"],
            ["app.messages.id"],
            name=op.f("fk_assistant_runs_user_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_runs")),
        sa.UniqueConstraint(
            "assistant_message_id", name=op.f("uq_assistant_runs_assistant_message_id")
        ),
        sa.UniqueConstraint(
            "user_message_id", name=op.f("uq_assistant_runs_user_message_id")
        ),
        schema="app",
    )
    op.create_index(
        "ix_assistant_runs_status_lease",
        "assistant_runs",
        ["status", "lease_expires_at"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_assistant_runs_status_lease", table_name="assistant_runs", schema="app"
    )
    op.drop_table("assistant_runs", schema="app")
    # ### end Alembic commands ###
