"""create trips table

Revision ID: 7e785b650b71
Revises: 4f7571eb0cd0
Create Date: 2026-08-26 21:13:49.678245

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e785b650b71"
down_revision: str | Sequence[str] | None = "4f7571eb0cd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("origin", sa.String(length=120), nullable=True),
        sa.Column("destination", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'planned', 'archived')", name=op.f("ck_trips_status")
        ),
        sa.CheckConstraint(
            "char_length(btrim(destination)) BETWEEN 2 AND 120",
            name=op.f("ck_trips_destination_length"),
        ),
        sa.CheckConstraint("end_date > start_date", name=op.f("ck_trips_date_order")),
        sa.CheckConstraint(
            "origin IS NULL OR char_length(btrim(origin)) BETWEEN 2 AND 120",
            name=op.f("ck_trips_origin_length"),
        ),
        sa.CheckConstraint(
            "title IS NULL OR char_length(btrim(title)) BETWEEN 1 AND 160",
            name=op.f("ck_trips_title_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_trips_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
        schema="app",
    )
    op.create_index(
        "ix_trips_user_status_start_date",
        "trips",
        ["user_id", "status", "start_date"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_trips_user_updated_at",
        "trips",
        ["user_id", "updated_at"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trips_user_updated_at", table_name="trips", schema="app")
    op.drop_index("ix_trips_user_status_start_date", table_name="trips", schema="app")
    op.drop_table("trips", schema="app")
    # ### end Alembic commands ###
