"""enforce one assistant reply per user message

Revision ID: 8232604507a7
Revises: 0b78ccc3c382
Create Date: 2026-08-17 14:23:16.235175

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8232604507a7"
down_revision: str | Sequence[str] | None = "0b78ccc3c382"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_messages_reply_to_message_id"),
        "messages",
        ["reply_to_message_id"],
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_messages_reply_to_message_id"),
        "messages",
        schema="app",
        type_="unique",
    )
    # ### end Alembic commands ###
