"""create itineraries and itinerary items tables

Revision ID: db5b0ae0df09
Revises: 7e785b650b71
Create Date: 2026-08-27 16:59:27.628322

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db5b0ae0df09"
down_revision: str | Sequence[str] | None = "7e785b650b71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "itineraries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'saved', 'superseded')",
            name=op.f("ck_itineraries_status"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_itineraries_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["app.trips.id"],
            name=op.f("fk_itineraries_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itineraries")),
        sa.UniqueConstraint(
            "trip_id",
            "version",
            name=op.f("uq_itineraries_trip_version"),
        ),
        schema="app",
    )
    op.create_index(
        "ix_itineraries_trip_created_at",
        "itineraries",
        ["trip_id", "created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_itineraries_one_saved_per_trip",
        "itineraries",
        ["trip_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("status = 'saved'"),
    )
    op.create_table(
        "itinerary_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("itinerary_id", sa.Uuid(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location_name", sa.String(length=200), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('flight', 'hotel', 'place', 'activity', 'meal', 'transfer', 'note')",
            name=op.f("ck_itinerary_items_item_type"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(title)) BETWEEN 1 AND 200",
            name=op.f("ck_itinerary_items_title_length"),
        ),
        sa.CheckConstraint(
            "day_number >= 1", name=op.f("ck_itinerary_items_day_number_positive")
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_itinerary_items_time_order"),
        ),
        sa.CheckConstraint(
            "position >= 1", name=op.f("ck_itinerary_items_position_positive")
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["app.itineraries.id"],
            name=op.f("fk_itinerary_items_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itinerary_items")),
        sa.UniqueConstraint(
            "itinerary_id",
            "day_number",
            "position",
            name=op.f("uq_itinerary_items_itinerary_day_position"),
        ),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itinerary_items", schema="app")
    op.drop_index(
        "uq_itineraries_one_saved_per_trip",
        table_name="itineraries",
        schema="app",
        postgresql_where=sa.text("status = 'saved'"),
    )
    op.drop_index(
        "ix_itineraries_trip_created_at", table_name="itineraries", schema="app"
    )
    op.drop_table("itineraries", schema="app")
    # ### end Alembic commands ###
