"""add itinerary source message idempotency

Revision ID: fbc765d13a3b
Revises: 4bd392a8d0c1
Create Date: 2026-08-28 14:10:58.329006

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbc765d13a3b"
down_revision: str | Sequence[str] | None = "4bd392a8d0c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itineraries",
        sa.Column("source_message_id", sa.Uuid(), nullable=True),
        schema="app",
    )
    op.create_unique_constraint(
        "uq_itineraries_source_message",
        "itineraries",
        ["source_message_id"],
        schema="app",
    )
    op.create_foreign_key(
        op.f("fk_itineraries_source_message_id_messages"),
        "itineraries",
        "messages",
        ["source_message_id"],
        ["id"],
        source_schema="app",
        referent_schema="app",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_itineraries_source_message_id_messages"),
        "itineraries",
        schema="app",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_itineraries_source_message", "itineraries", schema="app", type_="unique"
    )
    op.drop_column("itineraries", "source_message_id", schema="app")
    # ### end Alembic commands ###
