"""Structured model output for itinerary generation."""

from collections import defaultdict

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)

from app.domain.itineraries import (
    MAX_ITINERARY_ITEMS,
    ItineraryItemDraft,
)
from app.domain.itineraries import (
    ItineraryActivity as GeneratedItineraryItem,
)


class GeneratedItinerary(BaseModel):
    """Validated structured itinerary generated by the model."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    summary: str = Field(min_length=1, max_length=500)
    items: list[GeneratedItineraryItem] = Field(
        min_length=1,
        max_length=MAX_ITINERARY_ITEMS,
    )


def to_itinerary_item_drafts(
    generated: GeneratedItinerary,
) -> list[ItineraryItemDraft]:
    """Assign deterministic positions without trusting the model."""

    day_positions: dict[int, int] = defaultdict(int)
    drafts: list[ItineraryItemDraft] = []

    for item in generated.items:
        day_positions[item.day_number] += 1

        drafts.append(
            ItineraryItemDraft(
                **item.model_dump(),
                position=day_positions[item.day_number],
            )
        )

    return drafts
