"""Structured model output for itinerary generation."""

from collections import defaultdict
from typing import Self

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    model_validator,
)

from app.domain.itineraries import (
    ItineraryItemDraft,
    ItineraryItemType,
)


class GeneratedItineraryItem(BaseModel):
    """One model-generated itinerary item before position assignment."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    day_number: int = Field(ge=1)
    item_type: ItineraryItemType
    title: str = Field(min_length=1, max_length=200)
    description: str | None = Field(
        default=None,
        min_length=1,
        max_length=2000,
    )
    location_name: str | None = Field(
        default=None,
        min_length=1,
        max_length=200,
    )
    starts_at: AwareDatetime | None = None
    ends_at: AwareDatetime | None = None

    @model_validator(mode="after")
    def validate_time_order(self) -> Self:
        """Require the end time to follow the start time."""

        if (
            self.starts_at is not None
            and self.ends_at is not None
            and self.ends_at <= self.starts_at
        ):
            raise ValueError("ends_at must be after starts_at")

        return self


class GeneratedItinerary(BaseModel):
    """Validated structured itinerary generated by the model."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    summary: str = Field(min_length=1, max_length=500)
    items: list[GeneratedItineraryItem] = Field(
        min_length=1,
        max_length=200,
    )


def to_itinerary_item_drafts(
    generated: GeneratedItinerary,
) -> list[ItineraryItemDraft]:
    """Assign deterministic positions without trusting the model."""

    day_positions: dict[int, int] = defaultdict(int)
    drafts: list[ItineraryItemDraft] = []

    for item in generated.items:
        day_positions[item.day_number] += 1

        drafts.append(
            ItineraryItemDraft(
                **item.model_dump(),
                position=day_positions[item.day_number],
            )
        )

    return drafts
